pipeline{
    
    agent any
   tools {
        maven 'M3'
        jdk 'JAVA_HOME'
    }
    stages{
       stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${JAVA_HOME}"
                    echo "M2_HOME = ${M3}"
                '''
            }
        }
        
            stage('Checkout code') {
                 steps {
                 checkout scm
                 }
             }
        
        
        
       
       
      
    }
}
