pipeline{
    environment{
        registry = "grjyoshna/docker_test"
        registryCredential = "dockerhub"
    }
    agent any
    stages{
            stage('Checkout code') {
                 steps {
                 checkout scm
                 }
             }
        
       
       
        stage('Building Image'){
            steps{
                script{
                    docker.build registry + ":$BUILD_NUMBER"
                }
            }
        }
    }
}
